name: Build CI

on:
  push:
    branches: [master]
    paths:
      - "**"
      - "triggerBuild"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - run: npm install -g expo-cli

      - run: git config --global user.name 'Han Lin Yap'

      - run: git config --global user.email 'codler@users.noreply.github.com'

      - run: git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git

      - run: npm run deploy
